# Generated by Django 5.2.9 on 2025-12-27 15:29

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='earnings',
            new_name='earnings_amount',
        ),
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_shift_per_day'),
        ),
    ]
