# Generated by Django 5.2.9 on 2025-12-27 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_api', '0002_rename_earnings_shift_earnings_amount_alter_shift_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('FUEL', 'Fuel'), ('REPAIR', 'Repair'), ('PARKING', 'Parking'), ('COMMISSION', 'Commission'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
