# Generated by Django 5.2.9 on 2025-12-27 15:56

import datetime
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_api', '0003_alter_expense_expense_type_alter_expense_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='current_achieved',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='target_amount',
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='daily_target_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_goal_per_day'),
        ),
    ]
