# Generated by Django 5.2.9 on 2025-12-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_api', '0004_remove_savingsgoal_current_achieved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='daily_target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='date',
            field=models.DateField(),
        ),
    ]
