# Generated by Django 5.2.9 on 2025-12-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_api', '0005_alter_savingsgoal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='archived_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='archived_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
