# Generated by Django 5.2.9 on 2025-12-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_api', '0006_expense_archived_at_shift_archived_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='daily_target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='shift',
            name='earnings_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
