# Generated by Django 5.2.9 on 2025-12-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_api', '0007_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shift',
            name='unique_shift_per_day',
        ),
    ]
