# Generated by Django 5.2.9 on 2026-01-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_api', '0008_remove_shift_unique_shift_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='platform',
            field=models.CharField(choices=[('UBER', 'Uber'), ('ZOMATO', 'Zomato'), ('SWIGGY', 'Swiggy'), ('RAPIDO', 'Rapido'), ('MANUAL', 'Manual')], db_index=True, default='MANUAL', max_length=20),
        ),
    ]
