# Generated by Django 5.2.9 on 2026-01-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0002_invoice_customer_invoice_payment_mode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='invoice_item_quantity_non_negative'),
        ),
    ]
